name: Setup unit test
description: Download Maven caches needed for unit tests

inputs:
  jdk-dist:
    description: JDK distribution
    required: false
    default: temurin
  jdk-version:
    description: JDK version
    required: false
    default: 17

runs:
  using: composite
  steps:
    - id: setup-java
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.jdk-dist }}
        java-version: ${{ inputs.jdk-version }}

      # Can we own this?
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.BEANCI_GITHUB_SSH_KEY_ED25519_BINHLE410 }}

    - name: Set author identity
      run: |
        git config --global user.email "bot@peterbean.net"
        git config --global user.name "BeanBot"

    - name: Init Submodules
      run: |
        git submodule init master/keycloak
        git submodule update master/keycloak



    - id: maven-cache
      name: Maven cache
      uses: ./.github/actions/master/maven-cache
